### ISSUE TITLE
Add feature to create Plex collections from Trakt lists

### ISSUE THREAD

**Issue by gotson** [trakt/Plex-Trakt-Scrobbler#111]
It would be awesome to have the plugin automatically create/sync Plex collections from Trakt liked lists.
For example if on trakt i liked the list _Indiana Jones Collection_ (http://trakt.tv/lists/tmdb/indiana-jones-collection), that would create a collection inside Plex with the same name, containing movies that i have on my Plex media center.

**Comment by baphled** [comment]
+1

**Comment by fuzeman** [comment]
[v0.9.10.11-beta](https://github.com/trakt/Plex-Trakt-Scrobbler/releases/tag/v0.9.10.11-beta) now supports "pulling" liked/personal lists (and your watchlist) into plex as playlists.

I'm planning on implementing the "Collection" filter and having the ability to "push" playlist changes back to trakt in the future.

**Comment by tproenca** [comment]
Any news on this feature?

**Comment by fuzeman** [comment]
I'm currently working on a complete overhaul of the syncing system in the plugin, so will keep this in mind during the overhaul to ensure we can support this in the future.

Displaying Trakt.tv lists under the "Collection" filter is a bit difficult as this would require a custom metadata agent that can retrieve your personal/liked lists. I would like to see this supported, but currently this is low priority due to it's complexity.

**Comment by tproenca** [comment]
Thanks fuzeman for having the time to reply. Much appreciated!

**Comment by gotson** [comment]
However i see in the recent versions that one can sync liked lists, and they will show in the Playlist section. That's already nice :)

**Comment by M0UL** [comment]
any news on this?

**Comment by robot2xl** [comment]
any news on this?

**Comment by Herjar** [comment]
Still being worked on?
