### ISSUE TITLE
Clean Collection/Collection Sync Incorrect

### ISSUE THREAD

**Issue by mbeckford88** [trakt/Plex-Trakt-Scrobbler#183]
Hi Guys,

It's looking like since the trakt 2.0 API update that Cleaning a Collection no longer works?

I've removed all media from my collection (just moved the files somewhere else), updated library so my collection clears and have the Sync - Clean Collection option enabled, but then on trakt everything still shows up?

Also related, the collection numbers don't sync up (my plex library reports 333 episodes, my trakt library measures at 308 so some are going missing.

Anyone else have a similar issue?

Mark

**Comment by fuzeman** [comment]
You might need to have at least one item in your plex library for the sync to actually start.

This issue just reminded me this bug still exists (it's been around for a year), will have this fixed in the next release.

**Comment by mbeckford88** [comment]
Cool, tried again with a single item in the library to sync with and yea still not accurate.

Let me know if you need any logs to help out.

**Comment by fuzeman** [comment]
Sorry, kinda forgot about this issue..

----------------------------

Comparing my trakt.tv collection against plex actually shows trakt has 47 more episodes, this is likely due to multi-episode files (S01E01E02, etc..) that plex can't discover properly. So, collection syncing seems to be working correctly on my system.

To figure out what's happening on your system, could you supply the plugin log files after running another sync. See [this](https://github.com/fuzeman/Plex-Trakt-Scrobbler/wiki/Support#log-files) page for more details on the location of them.

**Comment by mbeckford88** [comment]
Embarrassingly I think I found the issue, I had a few episodes that plex detected but weren't mapped to trakt...

Removed them from my library and my plex numbers now match up, blame some really obscure TV shows it seems!
