### ISSUE TITLE
Movie is getting continual play counts added to Trakt on a daily basis

### ISSUE THREAD

**Issue by bonyboy** [trakt/Plex-Trakt-Scrobbler#218]
Problem:
For some reason the same movie that I watched months ago keeps getting play counts added to it on a daily basis.  When I discovered this, I had 5200 plays.  Yesterday I deleted all of them and today I am already back up to 8.

My logs can be found [here](https://www.dropbox.com/sh/7r3loq9s0ef670x/AAD9t8Bq2MYRI7QwoBky4wa0a?dl=0&s=so).

[Trakt thread I started prior to opening this issue](https://trakt.tv/forums/general/topics/last-watched-on-profile)

[Trakt profile](https://trakt.tv/users/bonyboy)

**Comment by fuzeman** [comment]
This issue usually happens when there is a metadata mismatch between your plex server and trakt, ideally incorrectly matched media needs to be detected and ignored from syncs..

----------------------

To figure out what is causing this duplication issue, could you find the movie that is being duplicated in Plex/Web and do the following:

1. Open the "Info" dialog
![](http://i.imgur.com/aUcqXe9.gif)

2. Save the XML file
![](http://i.imgur.com/8G8tK8S.png)

3. Upload this file to Dropbox so I can review it.

**Comment by bonyboy** [comment]
[Here you go](https://www.dropbox.com/s/jdcxh9rx6dgg29a/21944.xml?dl=0)

And thank you, for all the work (and support) you do for this community.  I'm sorry it took an issue to come up for me to say this.

**Comment by fuzeman** [comment]
Your server has the movie incorrectly identified as http://www.imdb.com/title/tt2447276/, this can be fixed by using the "Fix Incorrect Match" option in Plex/Web.

The correct IMDb page for the movie at http://www.imdb.com/title/tt3478594/ has an incorrect release date listed though, this means trakt probably wasn't able to find the movie. I've submitted a change to IMDb to correct this, it will probably take a few days to be accepted.

Might still be able to stop this item from being scrobbled constantly in the plugin, need to test a few things out.

**Comment by fuzeman** [comment]
I've just released [v0.9.1.29](https://github.com/trakt/Plex-Trakt-Scrobbler/releases/tag/v0.9.1.29) and [v0.9.10.7-beta](https://github.com/trakt/Plex-Trakt-Scrobbler/releases/tag/v0.9.10.7-beta) which should stop syncs from constantly re-adding items to your watched history.

**Comment by bonyboy** [comment]
Awesome! I've loaded it up v0.9.10.7-beta and will clear out the "Plays" from Trakt for that movie (15 so far today)

Thank you for your help..
