### ISSUE TITLE
Full sync not not updating content of other users

### ISSUE THREAD

**Issue by saitoh183** [trakt/Plex-Trakt-Scrobbler#221]
Im trying to full sync my wifes account and it is not updating plex

Log: http://pastebin.com/7snN2LMK

**Comment by fuzeman** [comment]
Could you enable debug logging *(for ```Plugin``` and ```Libraries```)* via the plugin preferences in plex and upload a log file after another sync.

What kind of data isn't updating *(watched states, playback progress, ratings)*?

**Comment by saitoh183** [comment]
Well from what I can tell, its the watched state that isn't being pulled since her plex account has nothing watched yet. I will post the new log in about 1h from now

**Comment by saitoh183** [comment]
Here is the log: 

http://pastebin.com/CB0LwxkY

**Comment by fuzeman** [comment]
Have you tried a "Pull" sync? this will to compare everything in plex against your trakt data and apply any changes.

A "Full" or "Quick Pull" will only apply changes to your trakt profile since your last sync, this means data could be ignored if the plugin has already "seen" the change but wasn't able to apply it to plex *(sync cancelled, authentication error, etc..)*

----------------------------------------------------

The log is showing a large number of episodes marked as watched on trakt, but are unwatched in plex. So it appears to be retrieving the watched states correctly, but it hasn't applied them likely due to the issue detailed above.

**Comment by saitoh183** [comment]
going to give the Pull a try. Quick pull handed work either

**Comment by saitoh183** [comment]
The Pull sync worked. So for new accounts we should do a Pull Sync the first time?

**Comment by fuzeman** [comment]
> So for new accounts we should do a Pull Sync the first time?

The first full sync on new accounts *should* pull everything in correctly, a "Pull" sync for new accounts should only be required if the first sync fails or is cancelled.

That's how it's designed, there might be a bug causing this to fail though..

**Comment by saitoh183** [comment]
ic...well it worked ...i will monitor to see if the full sync works as i have it setup to do it in day intervals
