### ISSUE TITLE
not syncing?

### ISSUE THREAD

**Issue by mgroen1975** [trakt/Plex-Trakt-Scrobbler#235]
Hi there..

just installed trakt.tv plugin on my sinology Plex server, but even when i sync manually, nothing is synced on www.trakt.tv ?

what am i doing wrong?

**Comment by fuzeman** [comment]
Could you post the plugin log files here (upload to dropbox, or pastebin, etc..), see https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Log-files for the location of them.

**Comment by JourneyOver** [comment]
Has been happening to me as well for the past 3 days now, doesn't matter if I'm watching something or if I do a manual sync, 98% of the time it just wont push watched status to any trakt.tv

http://paste.ee/p/LdIy4
http://paste.ee/p/9qqPg
http://paste.ee/p/hfDvX

Three different logs, hopefully you can make something out with these three.

**Comment by fuzeman** [comment]
@JourneyOver

Looks like this episode was scrobbled correctly:
```
Sending action u'scrobble/pause' (account: <Account name: u'administrator'>, interface: u'scrobble', method: u'pause')
request: {u'progress': 21.97, u'episode': {u'season': 2, u'number': 6, u'title': u'Rise of the Villains: By Fire'}, u'show': {u'title': u'Gotham', u'ids': {u'tvdb': 274431}, u'year': 2015}}

Sending action u'scrobble/start' (account: <Account name: u'administrator'>, interface: u'scrobble', method: u'start')
request: {u'progress': 21.97, u'episode': {u'season': 2, u'number': 6, u'title': u'Rise of the Villains: By Fire'}, u'show': {u'title': u'Gotham', u'ids': {u'tvdb': 274431}, u'year': 2015}}

Sending action u'scrobble/pause' (account: <Account name: u'administrator'>, interface: u'scrobble', method: u'pause')
request: {u'progress': 100.0, u'episode': {u'season': 2, u'number': 6, u'title': u'Rise of the Villains: By Fire'}, u'show': {u'title': u'Gotham', u'ids': {u'tvdb': 274431}, u'year': 2015}}

Sending action u'scrobble/stop' (account: <Account name: u'administrator'>, interface: u'scrobble', method: u'stop')
request: {u'progress': 100.0, u'episode': {u'season': 2, u'number': 6, u'title': u'Rise of the Villains: By Fire'}, u'show': {u'title': u'Gotham', u'ids': {u'tvdb': 274431}, u'year': 2015}}
```

This episode was being scrobbled, but the Trakt API returned a server error:
```
Sending action u'scrobble/start' (account: <Account name: u'administrator'>, interface: u'scrobble', method: u'start')
request: {u'progress': 0.0, u'episode': {u'season': 1, u'number': 6, u'title': u'Cede Your Soul'}, u'show': {u'title': u'Blindspot', u'ids': {u'tvdb': 295647}, u'year': 2015}}
request failed: Server Error - "server error" (code: 500)

Sending action u'scrobble/stop' (account: <Account name: u'administrator'>, interface: u'scrobble', method: u'stop')
request: {u'progress': 99.99, u'episode': {u'season': 1, u'number': 6, u'title': u'Cede Your Soul'}, u'show': {u'title': u'Blindspot', u'ids': {u'tvdb': 295647}, u'year': 2015}}
request failed: Server Error - "server error" (code: 500)
```

--------------------------------------------------------------------------

The next sync didn't push the scrobble to trakt because it was detected as currently being watched *(there might be a bug with this detection?)*:
```
Item 1225 is currently being watched, ignoring push watched handler
```

Then the item was deleted, so the watched history would of been removed from plex:
```
[plex_activity.activity.Activity   ]:emit(event: 'websocket.timeline.deleted', args: ({u'itemID': 1225, u'rootItemID': 1223, u'sectionID': 2, u'parentItemID': 1224, u'title': u'Blindspot S01 E06', u'_elementType': u'TimelineEntry', u'state': 9, u'updatedAt': 1445962417, u'type': 4, u'metadataState': u'deleted'},), kwargs: {})
```

**Comment by JourneyOver** [comment]
Hmm that's odd as hell that it's showing the gotham episode as scrobbled correctly because I was forced to go and manually click on watch on trakt.tv for it to show correctly as just watching it normally and doing a manual sync didn't produce anything on trakt.tv.. 

Blindspot (which is both the server error one and one that was supposedly detected as being watched and then deleted) I had to go do the same thing but it seems like it was because a server error I guess though nothing popped up in the trakt plugin at all about any errors for the API or anything, and it's funny that it shows it as deleted in the third part because I did a sync and waited until it said that it was a success and noticed that it still didn't push data to trakt before I deleted the item and just went on trakt and manually clicked on watched..

I have not gotten a single error message in the past couple days about any problems connecting to trakt or it's api at all when I check to see why it didn't send watched status to trakt, every time I check it always came up as showing success even when doing a manual sync even if nothing is actually pushed to trakt.

**Comment by mgroen1975** [comment]
i got my sync to work properly - i logget in and out of trakt.tv - now it works :-D
