### ISSUE TITLE
It wont sync

### ISSUE THREAD

**Issue by Kabloomasd** [trakt/Plex-Trakt-Scrobbler#339]
I think it stopped to work when I updated the plex server.

> File "E:\PMS APP DATA\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\models\m_trakt\account.py", line 74, in authorization
>     raise AccountAuthenticationError("Trakt account hasn't been authenticated")> 

![trakt](https://cloud.githubusercontent.com/assets/16331310/16622357/2ca9cc06-439a-11e6-9c80-98faa33b95f3.png)

[com.plexapp.plugins.trakttv (2).txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/350130/com.plexapp.plugins.trakttv.2.txt)

**Comment by fuzeman** [comment]
That warning is probably because your first (administrator) account hasn't been authenticated, this can just be ignored.

The log file doesn't indicate any Sync was triggered in the plugin, did you attempt to run a "Full" sync via the Plex/Web channel menu?

---------------

This error will be causing scrobbling issues though:
> ```
> WebSocket connection unavailable, activity monitoring not available
> ```

I'll need to do some testing to figure out what is causing this issue, could you let me know which version of Windows you are using?

**Comment by gdolla** [comment]
I think Windows  7 but I'm on a Mac I've integrated with parallels acces s

**Comment by Kabloomasd** [comment]
I reinstalled the plugin so many times maybe I didnt try to sync before I posted the log (I thought it might fix my problem) . And yes i am doing the sync via the channel menu.
When i sync it says its successfull. But the watched movies/episodes does not appear in trakt.

I am using Windows server 2012 R2.

**Comment by Kabloomasd** [comment]
It was the security in the web browser blocking it.
