### ISSUE TITLE
Stopped working or appearing in the channels

### ISSUE THREAD

**Issue by Mongoose69** [trakt/Plex-Trakt-Scrobbler#346]
Used to work o.k. But now doesn't show in the channels . I've tried reinstalling it without any luck

**Comment by fuzeman** [comment]
Which operating system are you running Plex Media Server on? (Windows, Ubuntu, Synology, etc..) and are you using the latest stable release of the plugin ([v1.0.3.3](https://github.com/trakt/Plex-Trakt-Scrobbler/releases/tag/v1.0.3.3))?

The latest plugin log file might help me identify what the issue is as well, see [this page](https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Log-files) for more details.
