### ISSUE TITLE
Sync multiple Plex users to one Trakt account

### ISSUE THREAD

**Issue by magicdude4eva** [trakt/Plex-Trakt-Scrobbler#379]
I have one Trakt.tv account which I would like to sync to/from. I can not figure this out. On my Plex Server I have 4 accounts:
- PlexAdmin (the main admin account - trakt should be synced)
- PlexWife (wife's account - trakt should be synced)
- PlexKid (kid's account - no sync)
- PlexGuest (guest account - no sync)

On "Global Filter - Users" I have setup "PlexAdmin,PlexWife" as we want to only sync trakt for those two users.

On the trakt-for-plex site I have setup:
- PlexAdmin with my trakt.tv account
- PlexWife with the Plex Pin

Under rules I have setup:
- No client rules
- One User rule "Account:Map -> Name:Any"

With the above the PlexAdmin account syncs from Trakt. The PlexWife account does not seem to sync and also does not seem to update watch status.

Could you confirm: How can I map multiple Plex accounts to one trakt account so that scrobble/sync for those accounts works?

**Comment by fuzeman** [comment]
Currently the plugin only supports syncing individual Plex and Trakt.tv accounts together, multiple Trakt.tv and/or Plex accounts can't be synchronized together.

------------

There has been a lot of discussions around this (#270, #327, #370, trakt-for-plex/configuration/issues/1), but nothing has been started yet due to it's complexity (will require a massive overhaul of the syncing system) and ultimately the lack of time I have available to work on this project these days (around 1 - 2 days per week).

I'll dedicate some more time next month to plan exactly what is required to get this implemented, but this would likely still be a number of months away from any stable implementation.

**Comment by magicdude4eva** [comment]
No problem. Thanks for the update @fuzeman - your plugin works well and you have done a fantastic job!

**Comment by gdolla** [comment]
Thank you!
