### ISSUE TITLE
Unwatched pull from Trakt.tv not working.

### ISSUE THREAD

**Issue by rodrigorf** [trakt/Plex-Trakt-Scrobbler#382]
I have only 1 movie in my Plex Server library and when i mark as watched in Trak.tv, the sync works fine! But if i mark "unwatched" in Trakt.tv the scrobbler does not update the Plex metadata. Anyone facing this problem? I'm running the _develop_ branch version. **log is attached**.

[log_trakt.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/667731/log_trakt.txt)

**Comment by fuzeman** [comment]
The plugin will only mark items as unwatched in Plex if the change to your profile watched history is detected during a "Full" or "Quick Pull" sync, this is currently the only way we can handle the conflict resolution between the two data sources.

Unwatched states may not be applied if a previous sync has already fetched the changes to your profile, but hasn't applied the changes correctly. (e.g. due to an error, or a "Pull" sync has been run instead)

I'm going to be looking into how we can improve this next year, but it will likely involve a fairly big overhaul to the syncing system.

**Comment by rodrigorf** [comment]
Hi @fuzeman, that was a really good explanation, it's a little bit clearer for me how it works. I'm gonna give it a try with "Full" and "Quick Pull" to see how it behaves. Anyway, thank for your help and congratulations for the plugin, let me know if i can help with anything. +1:
