### ISSUE TITLE
Plex syncing with other users

### ISSUE THREAD

**Issue by nanohits** [trakt/Plex-Trakt-Scrobbler#385]
I have a server and have several friends that access it. However when Trakt starts syncing, it also shows all of what my friends watched. I was under the impression it will just use the username thats watched the shows? If so, how can this be corrected?

One more question, I now notice that Plex continuously keeps updating the library. As I had just added this. Is it because it takes time to sync everything or does it do it all the time?

Thanks

**Comment by fuzeman** [comment]
> However when Trakt starts syncing, it also shows all of what my friends watched. I was under the impression it will just use the username thats watched the shows? If so, how can this be corrected?

See [this page](https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/FAQ---Scrobbling#2-why-are-videos-watched-by-other-users-being-scrobbled-to-my-profile) for details on how to filter out watching activity from other users.

If an automated or manual *sync* is pushing watching history for other users to your Trakt.tv profile, this would probably mean someone else is using your Plex account instead of logging into their own account.

> One more question, I now notice that Plex continuously keeps updating the library. As I had just added this. Is it because it takes time to sync everything or does it do it all the time?

The plugin doesn't trigger any library updates, this sounds more like an issue with Plex Media Server. The `Plex Media Server.log` file would probably indicate what is triggering the library updates, happy to have a look if you post it here.
