### ISSUE TITLE
Unable to retrieve "LocalAppDataPath" from server message in log

### ISSUE THREAD

**Issue by jpborjas** [trakt/Plex-Trakt-Scrobbler#409]
I just installed this channel, and I'm getting the error (among other messages):

2017-02-08 17:18:49,763 - plex_activity.sources.s_logging.main (700005955000) :  INFO (plex_activity.sources.s_logging.main:1159) - Unable to retrieve "LocalAppDataPath" from server

What is that?

I have hundreds of movies and TV shows. How do I know this is working? I just looked at my Trakt.tv , and under Movies, the movies I've Watched on Plex, or that exist in my Plex Library, are not marked as Watched or Collected in Trakt. Please find my log attached. 
[com.plexapp.plugins.trakttv.log.zip](https://github.com/trakt/Plex-Trakt-Scrobbler/files/762142/com.plexapp.plugins.trakttv.log.zip)

**Comment by fuzeman** [comment]
> ```
> ...Unable to retrieve "LocalAppDataPath" from server
> ```

This specific message isn't of concern, it just means the plugin is falling back to the default data locations for the logging activity source.

--------------

```
Found 17 unsupported movie(s)
```

```
Found 1 unsupported show(s)
```

These messages indicate you have some media in your plex libraries that aren't supported by the plugin (unsupported metadata agent, unmatched item, etc..).

---------

```
Invalid "title" or "year" attribute on <u'Xuxa S\xf3 Para Baixinhos' (None)>
Invalid "title" or "year" attribute on <u'Xuxa S\xf3 Para Baixinhos' (None)>
Invalid "title" or "year" attribute on <u'Xuxa S\xf3 Para Baixinhos 3' (None)>
Invalid "title" or "year" attribute on <u'Xuxa S\xf3 Para Baixinhos 3' (None)>
Invalid "title" or "year" attribute on <u'Xuxa S\xf3 Para Baixinhos 2' (None)>
Invalid "title" or "year" attribute on <u'Xuxa S\xf3 Para Baixinhos 2' (None)>
Invalid "title" or "year" attribute on <u'The New Yoda Chronicles: Escape from the Jedi Temple' (None)>
Invalid "title" or "year" attribute on <u'The New Yoda Chronicles: Escape from the Jedi Temple' (None)>
```

```
Unsupported agent: local (16 items)
```

Looks like these items haven't been matched in your plex libraries, these can be fixed by running a "Refresh" on your library or by using "Fix Incorrect Match" on each item in Plex/Web.

--------

```
Unsupported metadata agent: com.gracenote.onconnect
```

The Gracenote metadata agent isn't supported by the plugin, will be investigating if this can be supported in the future.

**Comment by jpborjas** [comment]
Excellent, thanks.
